In [90]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
from sklearn.model_selection import train_test_split
from sklearn import preprocessing
from sklearn.linear_model import LinearRegression
linear=LinearRegression()

In [2]:
df=pd.read_csv('Cleaned_data.csv')

In [3]:
df.head()

Unnamed: 0 property_type     price     location       city  \
0           0          Flat  10000000         G-10  Islamabad   
1           1          Flat   6900000         E-11  Islamabad   
2           2         House  16500000         G-15  Islamabad   
3           4         House   7000000  DHA Defence  Islamabad   
4           7          Flat   7800000         E-11  Islamabad   

       province_name   latitude  longitude  baths  bedrooms  date_added  \
0  Islamabad Capital  33.679890  73.012640      2         2  2019-02-04   
1  Islamabad Capital  33.700993  72.971492      3         3  2019-05-04   
2  Islamabad Capital  33.631486  72.926559      6         5  2019-07-17   
3  Islamabad Capital  33.492591  73.301339      3         3  2019-07-10   
4  Islamabad Capital  33.698244  72.984238      2         2  2019-05-05   

   Size in Marla  
0            4.0  
1            5.6  
2            8.0  
3            8.0  
4            6.2

In [4]:
df.columns

Index(['Unnamed: 0', 'property_type', 'price', 'location', 'city',
       'province_name', 'latitude', 'longitude', 'baths', 'bedrooms',
       'date_added', 'Size in Marla'],
      dtype='object')

In [5]:
df.drop(['Unnamed: 0'],axis=1,inplace=True)

In [7]:
df.drop(['location'],axis=1,inplace=True)

In [8]:
#Rearrange values
values=['date_added','property_type',  'Size in Marla','city', 'province_name',
       'latitude', 'longitude', 'baths', 'bedrooms','price'
       ]

In [9]:
df=df[values]

In [10]:
df.head()

date_added property_type  Size in Marla       city      province_name  \
0  2019-02-04          Flat            4.0  Islamabad  Islamabad Capital   
1  2019-05-04          Flat            5.6  Islamabad  Islamabad Capital   
2  2019-07-17         House            8.0  Islamabad  Islamabad Capital   
3  2019-07-10         House            8.0  Islamabad  Islamabad Capital   
4  2019-05-05          Flat            6.2  Islamabad  Islamabad Capital   

    latitude  longitude  baths  bedrooms     price  
0  33.679890  73.012640      2         2  10000000  
1  33.700993  72.971492      3         3   6900000  
2  33.631486  72.926559      6         5  16500000  
3  33.492591  73.301339      3         3   7000000  
4  33.698244  72.984238      2         2   7800000

### Creating dummies

In [11]:
#property_type
df.property_type.unique()

array(['Flat', 'House', 'Penthouse', 'Lower Portion', 'Upper Portion',
       'Farm House'], dtype=object)

In [12]:
dummies=pd.get_dummies(df['property_type'],drop_first=True)

In [13]:
dummies

Flat  House  Lower Portion  Penthouse  Upper Portion
0         1      0              0          0              0
1         1      0              0          0              0
2         0      1              0          0              0
3         0      1              0          0              0
4         1      0              0          0              0
...     ...    ...            ...        ...            ...
82962     0      1              0          0              0
82963     1      0              0          0              0
82964     0      1              0          0              0
82965     0      1              0          0              0
82966     0      1              0          0              0

[82967 rows x 5 columns]

In [22]:
#Check for errors
dummies['check']=dummies.sum(axis=1)
dummies

Flat  House  Lower Portion  Penthouse  Upper Portion  check
0         1      0              0          0              0      8
1         1      0              0          0              0      8
2         0      1              0          0              0      8
3         0      1              0          0              0      8
4         1      0              0          0              0      8
...     ...    ...            ...        ...            ...    ...
82962     0      1              0          0              0      8
82963     1      0              0          0              0      8
82964     0      1              0          0              0      8
82965     0      1              0          0              0      8
82966     0      1              0          0              0      8

[82967 rows x 6 columns]

In [26]:
dummies['check'].unique()

array([8, 0], dtype=int64)

In [27]:
dummies.drop(['check'],axis=1,inplace=True)

In [28]:
df=pd.concat([df,dummies],axis=1)

In [29]:
df.head()

date_added property_type  Size in Marla       city      province_name  \
0  2019-02-04          Flat            4.0  Islamabad  Islamabad Capital   
1  2019-05-04          Flat            5.6  Islamabad  Islamabad Capital   
2  2019-07-17         House            8.0  Islamabad  Islamabad Capital   
3  2019-07-10         House            8.0  Islamabad  Islamabad Capital   
4  2019-05-05          Flat            6.2  Islamabad  Islamabad Capital   

    latitude  longitude  baths  bedrooms     price  Flat  House  \
0  33.679890  73.012640      2         2  10000000     1      0   
1  33.700993  72.971492      3         3   6900000     1      0   
2  33.631486  72.926559      6         5  16500000     0      1   
3  33.492591  73.301339      3         3   7000000     0      1   
4  33.698244  72.984238      2         2   7800000     1      0   

   Lower Portion  Penthouse  Upper Portion  
0              0          0              0  
1              0          0              0  
2              0          0              0  
3              0          0              0  
4              0          0              0

In [33]:
#City
df['city'].unique()

array(['Islamabad', 'Lahore', 'Faisalabad', 'Rawalpindi', 'Karachi'],
      dtype=object)

In [35]:
city_dummies=pd.get_dummies(df['city'],drop_first=True)

In [36]:
city_dummies

Islamabad  Karachi  Lahore  Rawalpindi
0              1        0       0           0
1              1        0       0           0
2              1        0       0           0
3              1        0       0           0
4              1        0       0           0
...          ...      ...     ...         ...
82962          0        1       0           0
82963          0        1       0           0
82964          0        1       0           0
82965          0        1       0           0
82966          0        1       0           0

[82967 rows x 4 columns]

In [37]:
#check
city_dummies['check']=city_dummies.sum(axis=1)
city_dummies

Islamabad  Karachi  Lahore  Rawalpindi  check
0              1        0       0           0      1
1              1        0       0           0      1
2              1        0       0           0      1
3              1        0       0           0      1
4              1        0       0           0      1
...          ...      ...     ...         ...    ...
82962          0        1       0           0      1
82963          0        1       0           0      1
82964          0        1       0           0      1
82965          0        1       0           0      1
82966          0        1       0           0      1

[82967 rows x 5 columns]

In [38]:
city_dummies['check'].unique()

array([1, 0], dtype=int64)

In [39]:
city_dummies.drop(['check'],axis=1)

Islamabad  Karachi  Lahore  Rawalpindi
0              1        0       0           0
1              1        0       0           0
2              1        0       0           0
3              1        0       0           0
4              1        0       0           0
...          ...      ...     ...         ...
82962          0        1       0           0
82963          0        1       0           0
82964          0        1       0           0
82965          0        1       0           0
82966          0        1       0           0

[82967 rows x 4 columns]

In [40]:
df=pd.concat([df,city_dummies],axis=1)

In [41]:
df.head()

date_added property_type  Size in Marla       city      province_name  \
0  2019-02-04          Flat            4.0  Islamabad  Islamabad Capital   
1  2019-05-04          Flat            5.6  Islamabad  Islamabad Capital   
2  2019-07-17         House            8.0  Islamabad  Islamabad Capital   
3  2019-07-10         House            8.0  Islamabad  Islamabad Capital   
4  2019-05-05          Flat            6.2  Islamabad  Islamabad Capital   

    latitude  longitude  baths  bedrooms     price  Flat  House  \
0  33.679890  73.012640      2         2  10000000     1      0   
1  33.700993  72.971492      3         3   6900000     1      0   
2  33.631486  72.926559      6         5  16500000     0      1   
3  33.492591  73.301339      3         3   7000000     0      1   
4  33.698244  72.984238      2         2   7800000     1      0   

   Lower Portion  Penthouse  Upper Portion  Islamabad  Karachi  Lahore  \
0              0          0              0          1        0       0   
1              0          0              0          1        0       0   
2              0          0              0          1        0       0   
3              0          0              0          1        0       0   
4              0          0              0          1        0       0   

   Rawalpindi  check  
0           0      1  
1           0      1  
2           0      1  
3           0      1  
4           0      1

In [42]:
df.province_name.unique()

array(['Islamabad Capital', 'Punjab', 'Sindh'], dtype=object)

In [43]:
province_dummies=pd.get_dummies(df['province_name'],drop_first=True)

In [44]:
province_dummies

Punjab  Sindh
0           0      0
1           0      0
2           0      0
3           0      0
4           0      0
...       ...    ...
82962       0      1
82963       0      1
82964       0      1
82965       0      1
82966       0      1

[82967 rows x 2 columns]

In [46]:
province_dummies['check']=province_dummies.sum(axis=1)
province_dummies

Punjab  Sindh  check
0           0      0      0
1           0      0      0
2           0      0      0
3           0      0      0
4           0      0      0
...       ...    ...    ...
82962       0      1      1
82963       0      1      1
82964       0      1      1
82965       0      1      1
82966       0      1      1

[82967 rows x 3 columns]

In [47]:
province_dummies['check'].unique()

array([0, 1], dtype=int64)

In [48]:
province_dummies.drop(['check'],axis=1,inplace=True)

In [49]:
df=pd.concat([df,province_dummies],axis=1)

In [50]:
df.head()

date_added property_type  Size in Marla       city      province_name  \
0  2019-02-04          Flat            4.0  Islamabad  Islamabad Capital   
1  2019-05-04          Flat            5.6  Islamabad  Islamabad Capital   
2  2019-07-17         House            8.0  Islamabad  Islamabad Capital   
3  2019-07-10         House            8.0  Islamabad  Islamabad Capital   
4  2019-05-05          Flat            6.2  Islamabad  Islamabad Capital   

    latitude  longitude  baths  bedrooms     price  ...  Lower Portion  \
0  33.679890  73.012640      2         2  10000000  ...              0   
1  33.700993  72.971492      3         3   6900000  ...              0   
2  33.631486  72.926559      6         5  16500000  ...              0   
3  33.492591  73.301339      3         3   7000000  ...              0   
4  33.698244  72.984238      2         2   7800000  ...              0   

   Penthouse  Upper Portion  Islamabad  Karachi  Lahore  Rawalpindi  check  \
0          0              0          1        0       0           0      1   
1          0              0          1        0       0           0      1   
2          0              0          1        0       0           0      1   
3          0              0          1        0       0           0      1   
4          0              0          1        0       0           0      1   

   Punjab  Sindh  
0       0      0  
1       0      0  
2       0      0  
3       0      0  
4       0      0  

[5 rows x 22 columns]

In [52]:
df.drop(['check'],axis=1,inplace=True)

In [53]:
df.columns

Index(['date_added', 'property_type', 'Size in Marla', 'city', 'province_name',
       'latitude', 'longitude', 'baths', 'bedrooms', 'price', 'Flat', 'House',
       'Lower Portion', 'Penthouse', 'Upper Portion', 'Islamabad', 'Karachi',
       'Lahore', 'Rawalpindi', 'Punjab', 'Sindh'],
      dtype='object')

In [55]:
df.drop(['property_type','city','province_name'],axis=1,inplace=True)

In [56]:
df.head()

date_added  Size in Marla   latitude  longitude  baths  bedrooms     price  \
0  2019-02-04            4.0  33.679890  73.012640      2         2  10000000   
1  2019-05-04            5.6  33.700993  72.971492      3         3   6900000   
2  2019-07-17            8.0  33.631486  72.926559      6         5  16500000   
3  2019-07-10            8.0  33.492591  73.301339      3         3   7000000   
4  2019-05-05            6.2  33.698244  72.984238      2         2   7800000   

   Flat  House  Lower Portion  Penthouse  Upper Portion  Islamabad  Karachi  \
0     1      0              0          0              0          1        0   
1     1      0              0          0              0          1        0   
2     0      1              0          0              0          1        0   
3     0      1              0          0              0          1        0   
4     1      0              0          0              0          1        0   

   Lahore  Rawalpindi  Punjab  Sindh  
0       0           0       0      0  
1       0           0       0      0  
2       0           0       0      0  
3       0           0       0      0  
4       0           0       0      0

In [57]:
df.columns

Index(['date_added', 'Size in Marla', 'latitude', 'longitude', 'baths',
       'bedrooms', 'price', 'Flat', 'House', 'Lower Portion', 'Penthouse',
       'Upper Portion', 'Islamabad', 'Karachi', 'Lahore', 'Rawalpindi',
       'Punjab', 'Sindh'],
      dtype='object')

In [58]:
changing_values=[ 'Flat', 'House', 'Lower Portion', 'Penthouse',
       'Upper Portion','date_added', 'Size in Marla', 'latitude', 'longitude', 'baths',
       'bedrooms', 'price', 'Islamabad', 'Karachi', 'Lahore', 'Rawalpindi',
       'Punjab', 'Sindh']

In [59]:
df=df[changing_values]

In [60]:
df.head()

Flat  House  Lower Portion  Penthouse  Upper Portion  date_added  \
0     1      0              0          0              0  2019-02-04   
1     1      0              0          0              0  2019-05-04   
2     0      1              0          0              0  2019-07-17   
3     0      1              0          0              0  2019-07-10   
4     1      0              0          0              0  2019-05-05   

   Size in Marla   latitude  longitude  baths  bedrooms     price  Islamabad  \
0            4.0  33.679890  73.012640      2         2  10000000          1   
1            5.6  33.700993  72.971492      3         3   6900000          1   
2            8.0  33.631486  72.926559      6         5  16500000          1   
3            8.0  33.492591  73.301339      3         3   7000000          1   
4            6.2  33.698244  72.984238      2         2   7800000          1   

   Karachi  Lahore  Rawalpindi  Punjab  Sindh  
0        0       0           0       0      0  
1        0       0           0       0      0  
2        0       0           0       0      0  
3        0       0           0       0      0  
4        0       0           0       0      0

In [61]:
df.drop(['date_added'],axis=1,inplace=True)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\frame.py:4308: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(


In [62]:
df.head()

Flat  House  Lower Portion  Penthouse  Upper Portion  Size in Marla  \
0     1      0              0          0              0            4.0   
1     1      0              0          0              0            5.6   
2     0      1              0          0              0            8.0   
3     0      1              0          0              0            8.0   
4     1      0              0          0              0            6.2   

    latitude  longitude  baths  bedrooms     price  Islamabad  Karachi  \
0  33.679890  73.012640      2         2  10000000          1        0   
1  33.700993  72.971492      3         3   6900000          1        0   
2  33.631486  72.926559      6         5  16500000          1        0   
3  33.492591  73.301339      3         3   7000000          1        0   
4  33.698244  72.984238      2         2   7800000          1        0   

   Lahore  Rawalpindi  Punjab  Sindh  
0       0           0       0      0  
1       0           0       0      0  
2       0           0       0      0  
3       0           0       0      0  
4       0           0       0      0

In [63]:
data_preprocessed=df.copy()

### Machine learning

In [64]:
#Create target
target=data_preprocessed['price']

In [65]:
target

0        10000000
1         6900000
2        16500000
3         7000000
4         7800000
           ...   
82962    14000000
82963     4800000
82964    12500000
82965    11000000
82966     9000000
Name: price, Length: 82967, dtype: int64

In [70]:
unscaled_inputs=data_preprocessed.drop(['price'],axis=1)

In [71]:
unscaled_inputs

Flat  House  Lower Portion  Penthouse  Upper Portion  Size in Marla  \
0         1      0              0          0              0            4.0   
1         1      0              0          0              0            5.6   
2         0      1              0          0              0            8.0   
3         0      1              0          0              0            8.0   
4         1      0              0          0              0            6.2   
...     ...    ...            ...        ...            ...            ...   
82962     0      1              0          0              0            8.0   
82963     1      0              0          0              0            3.8   
82964     0      1              0          0              0            8.0   
82965     0      1              0          0              0            7.8   
82966     0      1              0          0              0            9.4   

        latitude  longitude  baths  bedrooms  Islamabad  Karachi  Lahore  \
0      33.679890  73.012640      2         2          1        0       0   
1      33.700993  72.971492      3         3          1        0       0   
2      33.631486  72.926559      6         5          1        0       0   
3      33.492591  73.301339      3         3          1        0       0   
4      33.698244  72.984238      2         2          1        0       0   
...          ...        ...    ...       ...        ...      ...     ...   
82962  25.058062  67.306626      3         3          0        1       0   
82963  25.022481  67.129082      0         2          0        1       0   
82964  25.017951  67.136393      0         3          0        1       0   
82965  25.013265  67.120818      0         3          0        1       0   
82966  25.113565  67.353811      3         3          0        1       0   

       Rawalpindi  Punjab  Sindh  
0               0       0      0  
1               0       0      0  
2               0       0      0  
3               0       0      0  
4               0       0      0  
...           ...     ...    ...  
82962           0       0      1  
82963           0       0      1  
82964           0       0      1  
82965           0       0      1  
82966           0       0      1  

[82967 rows x 16 columns]

In [72]:
from sklearn.preprocessing import StandardScaler

In [73]:
scaler=StandardScaler()

In [75]:
unscaled_inputs.drop(['latitude','longitude'],axis=1,inplace=True)

In [128]:
#Fit the data
scaler.fit(unscaled_inputs)

StandardScaler()

In [129]:
scaled_inputs=scaler.transform(unscaled_inputs)

In [130]:
scaled_inputs



array([[ 1.53612107, -1.40042976, -0.09904548, ..., -0.35436068,
        -0.96394809, -0.82192421],
       [ 1.53612107, -1.40042976, -0.09904548, ..., -0.35436068,
        -0.96394809, -0.82192421],
       [-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
        -0.96394809, -0.82192421],
       ...,
       [-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
        -0.96394809,  1.21665718],
       [-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
        -0.96394809,  1.21665718],
       [-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
        -0.96394809,  1.21665718]])

In [79]:
scaled_inputs.shape

(82967, 14)

In [80]:
unscaled_inputs.shape

(82967, 14)

In [81]:
unscaled_inputs.head()

Flat  House  Lower Portion  Penthouse  Upper Portion  Size in Marla  baths  \
0     1      0              0          0              0            4.0      2   
1     1      0              0          0              0            5.6      3   
2     0      1              0          0              0            8.0      6   
3     0      1              0          0              0            8.0      3   
4     1      0              0          0              0            6.2      2   

   bedrooms  Islamabad  Karachi  Lahore  Rawalpindi  Punjab  Sindh  
0         2          1        0       0           0       0      0  
1         3          1        0       0           0       0      0  
2         5          1        0       0           0       0      0  
3         3          1        0       0           0       0      0  
4         2          1        0       0           0       0      0

In [82]:
scaled_inputs.mean()

-3.866106911701411e-18

In [83]:
scaled_inputs.std()

0.9999999999999998

In [87]:
#Spliting the data into x and y
train_test_split(scaled_inputs,target)

[array([[-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
          1.03740026, -0.82192421],
        [-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
          1.03740026, -0.82192421],
        [-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
          1.03740026, -0.82192421],
        ...,
        [-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
          1.03740026, -0.82192421],
        [-0.65099035,  0.71406652, -0.09904548, ...,  2.82198355,
          1.03740026, -0.82192421],
        [ 1.53612107, -1.40042976, -0.09904548, ..., -0.35436068,
         -0.96394809,  1.21665718]]),
 array([[-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
          1.03740026, -0.82192421],
        [-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
          1.03740026, -0.82192421],
        [-0.65099035,  0.71406652, -0.09904548, ...,  2.82198355,
          1.03740026, -0.82192421],
        ...,
        [ 1.53612107, -1.40042976, -0.09904548, ..., -

In [88]:
x_train,x_test,y_train,y_test=train_test_split(scaled_inputs,target,train_size=0.8,random_state=20)

In [89]:
print(x_train.shape,y_train.shape)
print(x_test.shape,y_test.shape)

(66373, 14) (66373,)
(16594, 14) (16594,)


In [91]:
#Applying machine learning
linear.fit(x_train,y_train)

LinearRegression()

In [93]:
linear.score(x_train,y_train)

0.6004296093133876

In [100]:
#Creating the summary table and see the importance of the each value
coef=linear.coef_

In [99]:
intercept=linear.intercept_

In [96]:
unscaled_inputs.columns

Index(['Flat', 'House', 'Lower Portion', 'Penthouse', 'Upper Portion',
       'Size in Marla', 'baths', 'bedrooms', 'Islamabad', 'Karachi', 'Lahore',
       'Rawalpindi', 'Punjab', 'Sindh'],
      dtype='object')

In [97]:
summary_table=pd.DataFrame(columns=['Features'],data=unscaled_inputs.columns.values)

In [98]:
summary_table

Features
0            Flat
1           House
2   Lower Portion
3       Penthouse
4   Upper Portion
5   Size in Marla
6           baths
7        bedrooms
8       Islamabad
9         Karachi
10         Lahore
11     Rawalpindi
12         Punjab
13          Sindh

In [102]:
summary_table['Coefficient']=np.transpose(coef)

In [103]:
summary_table

Features   Coefficient
0            Flat -3.155585e+06
1           House -2.150549e+06
2   Lower Portion -7.249604e+05
3       Penthouse -3.991266e+05
4   Upper Portion -1.212619e+06
5   Size in Marla  3.728466e+06
6           baths  2.855320e+05
7        bedrooms  5.418706e+05
8       Islamabad -4.908271e+17
9         Karachi -3.718406e+17
10         Lahore  3.715587e+05
11     Rawalpindi -2.758359e+05
12         Punjab -7.682674e+17
13          Sindh -3.823950e+17

In [111]:
summary_table.index=summary_table.index+1

In [113]:
summary_table.loc[0]=['Intercept',linear.intercept_[0]]

IndexError: invalid index to scalar variable.

In [107]:
summary_table

Features   Coefficient
1            Flat -3.155585e+06
2           House -2.150549e+06
3   Lower Portion -7.249604e+05
4       Penthouse -3.991266e+05
5   Upper Portion -1.212619e+06
6   Size in Marla  3.728466e+06
7           baths  2.855320e+05
8        bedrooms  5.418706e+05
9       Islamabad -4.908271e+17
10        Karachi -3.718406e+17
11         Lahore  3.715587e+05
12     Rawalpindi -2.758359e+05
13         Punjab -7.682674e+17
14          Sindh -3.823950e+17

In [114]:
summary_table['Odd Ratio']=np.exp(summary_table.Coefficient)

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\arraylike.py:358: RuntimeWarning: overflow encountered in exp
  result = getattr(ufunc, method)(*inputs, **kwargs)


In [115]:
summary_table

Features   Coefficient  Odd Ratio
3            Flat -3.155585e+06        0.0
4           House -2.150549e+06        0.0
5   Lower Portion -7.249604e+05        0.0
6       Penthouse -3.991266e+05        0.0
7   Upper Portion -1.212619e+06        0.0
8   Size in Marla  3.728466e+06        inf
9           baths  2.855320e+05        inf
10       bedrooms  5.418706e+05        inf
11      Islamabad -4.908271e+17        0.0
12        Karachi -3.718406e+17        0.0
13         Lahore  3.715587e+05        inf
14     Rawalpindi -2.758359e+05        0.0
15         Punjab -7.682674e+17        0.0
16          Sindh -3.823950e+17        0.0

In [127]:
linear.predict(scaled_inputs)

array([ 5834647.1076507,  8844439.1076507, 16126615.1076507, ...,
       15374510.5994118, 15063086.5994118, 18016302.5994118])

In [119]:
x_train

array([[ 1.53612107, -1.40042976, -0.09904548, ..., -0.35436068,
        -0.96394809,  1.21665718],
       [ 1.53612107, -1.40042976, -0.09904548, ..., -0.35436068,
        -0.96394809,  1.21665718],
       [-0.65099035,  0.71406652, -0.09904548, ...,  2.82198355,
         1.03740026, -0.82192421],
       ...,
       [-0.65099035, -1.40042976, -0.09904548, ..., -0.35436068,
        -0.96394809,  1.21665718],
       [ 1.53612107, -1.40042976, -0.09904548, ..., -0.35436068,
        -0.96394809,  1.21665718],
       [-0.65099035,  0.71406652, -0.09904548, ..., -0.35436068,
        -0.96394809,  1.21665718]])

In [131]:
data_preprocessed

Flat  House  Lower Portion  Penthouse  Upper Portion  Size in Marla  \
0         1      0              0          0              0            4.0   
1         1      0              0          0              0            5.6   
2         0      1              0          0              0            8.0   
3         0      1              0          0              0            8.0   
4         1      0              0          0              0            6.2   
...     ...    ...            ...        ...            ...            ...   
82962     0      1              0          0              0            8.0   
82963     1      0              0          0              0            3.8   
82964     0      1              0          0              0            8.0   
82965     0      1              0          0              0            7.8   
82966     0      1              0          0              0            9.4   

       baths  bedrooms     price  Islamabad  Karachi  Lahore  Rawalpindi  \
0          2         2  10000000          1        0       0           0   
1          3         3   6900000          1        0       0           0   
2          6         5  16500000          1        0       0           0   
3          3         3   7000000          1        0       0           0   
4          2         2   7800000          1        0       0           0   
...      ...       ...       ...        ...      ...     ...         ...   
82962      3         3  14000000          0        1       0           0   
82963      0         2   4800000          0        1       0           0   
82964      0         3  12500000          0        1       0           0   
82965      0         3  11000000          0        1       0           0   
82966      3         3   9000000          0        1       0           0   

       Punjab  Sindh  
0           0      0  
1           0      0  
2           0      0  
3           0      0  
4           0      0  
...       ...    ...  
82962       0      1  
82963       0      1  
82964       0      1  
82965       0      1  
82966       0      1  

[82967 rows x 15 columns]